# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "66fbef27493a62d8035512da2ee741dc"
name = "sovs-checkout-validation"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sanrio-fromjp.myshopify.com"

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[pos]
embedded = false
